"""add_storygraph_edition_fields

Revision ID: 33dc0561f4c4
Revises: c8a2d7e4f1b9
Create Date: 2026-04-28 08:55:00.379109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dc0561f4c4'
down_revision: Union[str, Sequence[str], None] = 'c8a2d7e4f1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storygraph_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storygraph_edition_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('storygraph_pages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storygraph_details', schema=None) as batch_op:
        batch_op.drop_column('storygraph_pages')
        batch_op.drop_column('storygraph_edition_id')

    # ### end Alembic commands ###
